#  FAÇA UM PRGRAMA QUE MOSTRE NA TELA UMA CONTAGEM  REGRESSIVA PARA O ESTOURO DE FOGOS DE ARTIFÍCIO, INDO DE 10 ATÉ 0, COM UMA PAUSA DE 1 SEGUNDO ENTRE ELES.
 

import os # IMPORTANDO A BIBLIOTECA OS PARA USAR A FUNÇÃO SYSTEM
os.system('cls') # FUNÇÃO SYSTEM PARA LIMPAR A TELA TERMINAL

import time # IMPORTANDO A BIBLIOTECA TIME PARA USAR A FUNÇÃO SLEEP
for c in range (10,-1,-1): # CONTAGEM REGRESSIVA DE 10 ATÉ 0
    print(c) # MOSTRANDO O VALOR DE C
    time.sleep(1) # FUNÇÃO SLEEP PARA DAR UMA PAUSA DE 1 SEGUNDO
print(' ********************FOGOS ESTOURAAAANDO, MEUS PARABÉNS*******************************************!!!') # MENSAGEM DE FIM DA CONTAGEM
