#  FAÇA UM PROGRAMA QUE CALCULE A SOMA ENTRE TODOS OS NÚMEROS QUE SÃO MÚLTIPLOS DE 3 E QUE ESTÃO NO INTERVALO DE 1 ATÉ 500.

import os # IMPORTANDO A BIBLIOTECA OS PARA USAR A FUNÇÃO SYSTEM
os.system('cls') # FUNÇÃO SYSTEM PARA LIMPAR A TELA TERMINAL    

soma=0 # VARIAVEL SOMA PARA GUARDAR A SOMA DOS VALORES

for c in range(1,501): # REPETIÇÃO DE 1 ATÉ 500
    if c % 3 == 0: # SE O RESTO DA DIVISÃO DE C POR 3 FOR IGUAL A 0, ENTÃO C É MÚLTIPLO DE 3
        soma += c # SOMA O VALOR DE C NA VARIAVEL SOMA
print(f'A SOMA DE TODOS OS NÚMEROS MÚLTIPLOS DE 3, ENTRE 1 E 500 É -----> {soma} <-----') # MOSTRA O VALOR DA SOMA