# FAÇA UM PROGRAMA QUE MOSTRE NA TELA TODOS OS NÚMEROS PARES QUE ESTÃO NO INTERVALO ENTRE 1 E 50.

import os # IMPORTANDO A BIBLIOTECA OS PARA USAR A FUNÇÃO SYSTEM
os.system('cls') # FUNÇÃO SYSTEM PARA LIMPAR A TELA TERMINAL


for c in range(2,51,2): # CONTAGEM DE 2 ATÉ 50, PULANDO DE 2 EM 2
    print(c) # MOSTRANDO O VALOR DE C