# DESENVOLVA UM PROGRAMA QUE LEIA SEIS NÚMEROS INTEIROS E MOSTRE A SOMA APENAS DAQUELES QUE FOREM PARES. SE O VALOR DIGITADO FOR ÍMPAR, DESCONSIDERE-O.


import os # IMPORTANDO A BIBLIOTECA OS PARA USAR A FUNÇÃO SYSTEM
os.system('cls') # FUNÇÃO SYSTEM PARA LIMPAR A TELA TERMINAL


soma=0 # VARIAVEL SOMA PARA GUARDAR A SOMA DOS VALORES
for c in range(1,7): # REPETIÇÃO DE 1 ATÉ 6
    num=int(input(f'Digite o {c}º número: ')) # VARIAVEL NUM PARA GUARDAR O NÚMERO QUE O USUÁRIO DIGITAR
    if num % 2 == 0: # SE O RESTO DA DIVISÃO DE NUM POR 2 FOR IGUAL A 0, ENTÃO NUM É PAR
        soma += num # SOMA O VALOR DE NUM NA VARIAVEL SOMA
print(f'A SOMA DOS NÚMEROS PARES É: {soma}') # MOSTRA O VALOR DA SOMA
print(' @@@@@@@@@@@ FIM DO PROGRAMA, OBRIGADO POR USAR MEU PROGRAMA!!! @@@@@@@@@@@ ') # MENSAGEM DE FIM DO PROGRAMA